#!/bin/bash

# Purge Images (AMI) created with 'aws ec2 create-image' call

# Author:   Michal Ludvig <mludvig@logix.net.nz>
# License:  BSD
# Homepage: https://aws.nz/aws-utils/purge-images

function show_help() {
	cat << __EOF__
Usage: $0 [-h] [options]

Purge AMI (Images) older than a given date, optionally matching certain
filters.

   -d DATE      Date or Timestamp since the Unix Epoch. Images older
   -t TIMESTAMP than this will be deleted. DATE can be any date format
                accepted by GNU date(1) command, e.g. "3 days ago".

   -a AMI-ID    AMI ID to remove.

   -n NAME_REGEXP
                The AMI Name or Description must match NAME_REGEXP.

   -y           Yes, delete. Without this parameter the script only
                displays what would be deleted.

   -p PROFILE   AWS-CLI Profile name as defined in ~/.aws/config.
                Optional, will use default or instance meta-data if
                not specified.

   -h           Display help.

Visit https://aws.nz/aws-utils/purge-images for more info and examples.
__EOF__
	exit 1
}

function fatal() {
	echo $1 >&2
	exit 1
}

AWS=$(which aws 2>/dev/null)
test -z "${AWS}" && fatal "The 'aws' utility not found. Please install it or add its location to \$PATH"

JQ=$(which jq 2>/dev/null)
test -z "${JQ}" && fatal "The 'jq' utility not found. Please install it or add its location to \$PATH"

while getopts "a:d:n:p:t:yh" OPT; do
	case "${OPT}" in
	a)
		AMI_ID="${OPTARG}"
		;;
	d)
		DATE="${OPTARG}"
		;;
	n)
		NAME="${OPTARG}"
		;;
	p)
		AWS="${AWS} --profile=${OPTARG}"
		;;
	t)
		TIMESTAMP="${OPTARG}"
		;;
	y)
		YES_DELETE=1
		;;
	h)
		show_help
		;;
	esac
done

# Normalise date
test -n "${TIMESTAMP}" && TIMESTAMP=$(date +%s --date "@${TIMESTAMP}")
test -n "${DATE}" && TIMESTAMP=$(date +%s --date "${DATE}")
test -z "${TIMESTAMP}" && fatal "No date given, use -d or -t parameter. Or -h for help."

echo "Getting ready, this may take a while..."

IMAGES_JSON=$(${AWS} ec2 describe-images --owners=self ${AMI_ID:+ --filters Name=image-id,Values=${AMI_ID}})

# Filter images by date and InstanceId
IMAGES_JSON=$(${JQ} -r "[.Images[]
	| {
		ImageId: .ImageId,
		CreationDate: .CreationDate,
		CreationDateSec: .CreationDate|strptime(\"%Y-%m-%dT%H:%M:%S.000Z\")|mktime,
		Name: .Name,
		Description: .Description,
		Snapshots: [ .BlockDeviceMappings[].Ebs.SnapshotId ],
		SnapshotsSize: [ .BlockDeviceMappings[].Ebs.VolumeSize ] | add
	}
	| select(.CreationDateSec < ${TIMESTAMP} ${NAME:+ and ((.Name | test(\"${NAME}\")) or (.Description | test(\"${NAME}\"))) })]" <<< ${IMAGES_JSON})

if [ -z "${YES_DELETE}" ]; then
	${JQ} -r '.[] | @text "\(.ImageId)   \(.CreationDate)   \(.Name)   \(.SnapshotsSize) GB"' <<< ${IMAGES_JSON}
	exit 0
fi

echo "Deleting $(${JQ} -r '. | length' <<< ${IMAGES_JSON}) images ..."

AMIS=$(${JQ} -r '.[].ImageId' <<< ${IMAGES_JSON})

set -e

for AMI in ${AMIS}; do
	echo -n "Deleting: ${AMI}"
	${AWS} ec2 deregister-image --image-id ${AMI}
	for SNAP in $(${JQ} -r ".[] | select(.ImageId == \"${AMI}\") | .Snapshots[]" <<< ${IMAGES_JSON}); do
		echo -n " ${SNAP}"
		${AWS} ec2 delete-snapshot --snapshot-id ${SNAP}
	done
	echo
done
