#!/bin/sh

# By Michael Ludvig <mludvig@logix.net.nz> (c) 2016
# License: GPLv3

# List running instances and group them by Name
# Useful for AutoScaling groups, etc.
# Best to be placed in profile.d

set -e

aws ec2 describe-instances | jq -r '
# Right-pad string with spaces
def pad(width):
  tostring | if width > length then . + (width - length) * " " else . end;

# Display running instances Name and PrivateIpAddress
[
	.Reservations[].Instances[]
	| select(.State.Name == "running" and .Tags != null)
	| {
		"PrivateIpAddress": .PrivateIpAddress?,
		"Name": .Tags[] | select(.Key == "Name") | .Value,
	}
]
| sort_by(.Name)
| group_by(.Name)
| .[]
| {
	"FmtName": .[0].Name | pad(30),
	"FmtIpAddr": [ .[].PrivateIpAddress ] | join("  ")
}
| @text "\(.FmtName) \(.FmtIpAddr)"
'
