#!/bin/bash

# By Michael Ludvig <mludvig@logix.net.nz> (c) 2015
# License: GPLv3

# Fetch EC2 Role credentials from instance meta-data
# and print as bash-compatible export statements.
#
# Usage:
# 	eval $(./get-instance-credentials)
#	aws ...
#	s3cmd ...

ROLE_NAME=$(curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/)
curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/${ROLE_NAME} | jq -r '
	@text "export AWS_ACCESS_KEY_ID=\"\(.AccessKeyId)\"",
	@text "export AWS_SECRET_ACCESS_KEY=\"\(.SecretAccessKey)\"",
	@text "export AWS_SESSION_TOKEN=\"\(.Token)\""
'
