#!/bin/bash

# Create a VPC Endpoint to access AWS services without
# the need for Internet access.

# Author: Michael Ludvig <michael.ludvig@enterpriseit.co.nz>

set -e

function show_help() {
	cat << __EOF__
Usage: $0 [OPTIONS]

Create VPC and Subnets as defined in a config file.

   -p PROFILE   AWS-CLI Profile name as defined in ~/.aws/config.
                Optional, will use default or instance meta-data if
                not specified.

   -v VPC-ID    VPC ID where the Endpoint should be added.
                Optional, only needed if more than one VPC exists
                in the account.

   -r ROUTE-TABLE-ID
                Routing table where to install the Endpoint route.
                Optional, only needed if more than one Routing table
                exists in the VPC.

   -s SERVICE-ID
                Endpoint Service to attach to the VPC.
                Optional, only needed if more than one Endpoint Service
                is available in the AWS region.

   -h           Display help.

__EOF__
	exit 1
}

function cleanup() {
	rm -f ${TMPFILE}
}

function fatal() {
	echo $1 >&2
	exit 1
}

AWS=$(which aws 2>/dev/null)
TMPFILE=$(mktemp ${TMPDIR:-/tmp}/aws-utils.XXXXXXXX)
trap cleanup EXIT

test -z "${AWS}" && fatal "The 'aws' utility not found. Please install it or add its location to \$PATH"

while getopts "p:r:s:v:h" OPT; do
	case "${OPT}" in
	p)
		AWS="${AWS} --profile=${OPTARG}"
		;;
	r)
		ROUTETAB_ID="${OPTARG}"
		;;
	s)
		SERVICE_ID="${OPTARG}"
		;;
	v)
		VPC_ID="${OPTARG}"
		;;
	h)
		show_help
		;;
	esac
done

echo "Building configuration, this may take a while..."

# Determine if we have exactly one VPC to work with
FILTER=""
test -n "${VPC_ID}" && FILTER="--filter Name=vpc-id,Values=${VPC_ID}"
${AWS} ec2 describe-vpcs ${FILTER} | jq -f unfold-tags.jq > ${TMPFILE} || fatal "Unable to list VPCs"
case $(jq 'length' ${TMPFILE}) in
	0)
		fatal "No VPCs found or -v parameter invalid for this account"
		;;
	1)
		VPC_ID=$(jq -r '.[0].VpcId'  ${TMPFILE})
		;;
	*)
		echo "More than one VPC found, use -v VPC-ID to select one:" >&2
		jq -r '.[] | @text "\(.VpcId) \(.CidrBlock)   \(.TagName)"' ${TMPFILE} >&2
		exit 1
		;;
esac
echo "VPC: ${VPC_ID}"

# Determine if we have exactly one routing table to work with
FILTER="--filter Name=vpc-id,Values=${VPC_ID}"
test -n "${ROUTETAB_ID}" && FILTER="${FILTER} --filter Name=route-table-id,Values=${ROUTETAB_ID}"
${AWS} ec2 describe-route-tables ${FILTER} | jq -f unfold-tags.jq > ${TMPFILE} || fatal "Unable to list RouteTables"
case $(jq 'length' ${TMPFILE}) in
	0)
		fatal "No RouteTables found or -r parameter invalid for this VPC"
		;;
	1)
		RT_ID=$(jq -r '.[0].RouteTableId'  ${TMPFILE})
		;;
	*)
		echo "More than one RouteTable found, use -r RouteTable-ID to select one:" >&2
		jq -r '.[] | .RouteTableId' ${TMPFILE} >&2
		exit 1
		;;
esac
echo "Route Table: ${RT_ID}"

# Determine if we have exactly one service to work with
${AWS} ec2 describe-vpc-endpoint-services | jq -r '.ServiceNames[]' > ${TMPFILE}
if [ -n "${SERVICE_ID}" ]; then
	_ID=$(grep ${SERVICE_ID} ${TMPFILE})
	echo ${_ID} > ${TMPFILE}
fi
case $(grep -c com.amazonaws ${TMPFILE}) in
	0)
		fatal "No Endpint Services available. AWS is broken or -s parameter not invalid."
		;;
	1)
		SERVICE_ID=$(cat ${TMPFILE})
		;;
	*)
		echo "More than one Endpoint Service found, use -s Service-Name to select one:" >&2
		cat ${TMPFILE} >&2
		exit 1
		;;
esac
echo "Service: ${SERVICE_ID}"

# Create the endpoint
${AWS} ec2 create-vpc-endpoint --vpc-id ${VPC_ID} --route-table-ids ${RT_ID} --service-name ${SERVICE_ID} > ${TMPFILE}
VPCE_ID=$(jq -r '.VpcEndpoint.VpcEndpointId' ${TMPFILE})
echo "Done: ${VPCE_ID} has been created"
