#!/bin/bash

# Create a VPC Endpoint to access AWS services without
# the need for Internet access.

# Author: Michael Ludvig <michael.ludvig@enterpriseit.co.nz>

function show_help() {
	cat << __EOF__
Usage: $0 [-p PROFILE] [-v VPC-ID] [-r ROUTE-TABLE-ID] [-h]

Create VPC and Subnets as defined in a config file.

   -p PROFILE   AWS-CLI Profile name as defined in ~/.aws/config.
                Optional, will use default or instance meta-data if
                not specified.

   -v VPC-ID    VPC ID where the Endpoint should be added.
                Optional, only needed if more than one VPC exists
                in the account.

   -r ROUTE-TABLE-ID
                Routing table where to install the Endpoint route.
                Optional, only needed if more than one Routing table
                exists in the VPC.

   -h           Display help.

__EOF__
	exit 1
}

function cleanup() {
	rm -f ${TMPFILE}
}

function fatal() {
	echo $1 >&2
	exit 1
}

AWS=$(which aws 2>/dev/null)
TMPFILE=$(mktemp ${TMPDIR:-/tmp}/aws-utils.XXXXXXXX)
trap cleanup EXIT

test -z "${AWS}" && fatal "The 'aws' utility not found. Please install it or add its location to \$PATH"

while getopts "p:r:v:h" OPT; do
	case "${OPT}" in
	p)
		AWS="${AWS} --profile=${OPTARG}"
		;;
	r)
		ROUTETAB_ID="${OPTARG}"
		;;
	v)
		VPC_ID="${OPTARG}"
		;;
	h)
		show_help
		;;
	esac
done

# Determine if we have exactly one VPC to work with
FILTER=""
test -z "${VPC_ID}" || FILTER="--filter Name=vpc-id,Values=${VPC_ID}"
${AWS} ec2 describe-vpcs ${FILTER} | jq -f unfold-tags.jq > ${TMPFILE} || fatal "Unable to list VPCs"
case $(jq 'length' ${TMPFILE}) in
	0)
		fatal "No VPCs found or -v parameter invalid for this account"
		;;
	1)
		VPC_ID=$(jq -r '.[0].VpcId'  ${TMPFILE})
		;;
	*)
		echo "More than one VPC found, use -v VPC-ID to select one:" >&2
		jq -r '.[] | @text "\(.VpcId) \(.CidrBlock)   \(.TagName)"' ${TMPFILE} >&2
		exit 1
		;;
esac

# Determine if we have exactly one routing table to work with
FILTER="--filter Name=vpc-id,Values=${VPC_ID}"
test -z "${ROUTETAB_ID}" || FILTER="${FILTER} --filter Name=route-table-id,Values=${ROUTETAB_ID}"
${AWS} ec2 describe-route-tables ${FILTER} | jq -f unfold-tags.jq > ${TMPFILE} || fatal "Unable to list RouteTables"
case $(jq 'length' ${TMPFILE}) in
	0)
		fatal "No RouteTables found or -r parameter invalid for this VPC"
		;;
	1)
		RT_ID=$(jq -r '.[0].RouteTableId'  ${TMPFILE})
		;;
	*)
		echo "More than one RouteTable found, use -r RouteTable-ID to select one:" >&2
		jq -r '.[] | .RouteTableId' ${TMPFILE} >&2
		exit 1
		;;
esac

echo "${VPC_ID} - ${RT_ID}"
